<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eyebrow</string>
	</array>
	<key>name</key>
	<string>Eyebrow Templates</string>
	<key>patterns</key>
	<array>
		<!-- Include Standard HTML Syntax -->
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<!-- Comment tag -->
		<dict>
			<key>begin</key>
			<string>{{!</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.other.eyebrow.delimiter.comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>comment.block.jinja</string>
		</dict>
		<!-- Eyebrow -->
		<dict>
			<key>begin</key>
			<string>{{{?\s?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.other.eyebrow.delimiter.variable</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s?}}}?</string>
			<key>name</key>
			<string>meta.scope.eyebrow.variable</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<!-- Tags -->
				<dict>
					<key>match</key>
					<string>(%|#|\?|&lt;|\^)\s?((?!\w+\/)[a-zA-Z_]+)?</string>
					<key>captures</key>
					<dict>
						<!-- Tag symbol -->
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.eyebrow</string>
						</dict>
						<key>2</key>
						<!-- Custom tags -->
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
				</dict>
				<!-- Close tag -->
				<dict>
					<key>match</key>
					<string>(\/)(%|#|\?|&lt;)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.eyebrow</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment</string>
						</dict>
					</dict>
				</dict>
				<!-- Partial tag -->
				<dict>
					<key>match</key>
					<string>></string>
					<key>name</key>
					<string>punctuation.section.embedded</string>
				</dict>
				<!-- Unquoted path -->
				<dict>
				    <key>match</key>
				    <string>\s([^"]+?\/[a-zA-Z]+)([^}\s]+)</string>
				    <key>captures</key>
				    <dict>
				        <key>1</key>
				        <dict>
				            <key>name</key>
				            <string>string.include.partial</string>
				        </dict>
				        <key>2</key>
				        <dict>
				            <key>name</key>
				            <string>string.include.partial</string>
				        </dict>
				    </dict>
				</dict>
				<!-- Partial params -->
				<dict>
				    <key>match</key>
				    <string>([a-zA-Z_]+)([:])</string>
				    <key>captures</key>
				    <dict>
				        <key>1</key>
				        <dict>
				            <key>name</key>
				            <string>storage</string>
				        </dict>
				        <key>2</key>
				        <dict>
				            <key>name</key>
				            <string>comment</string>
				        </dict>
				    </dict>
				</dict>
				<!-- Extends tag -->
				<dict>
				    <key>match</key>
				    <string>(&lt;&lt;)\s([a-zA-Z_\/\.-]+)</string>
				    <key>captures</key>
				    <dict>
				        <key>1</key>
				        <dict>
				            <key>name</key>
				            <string>punctuation.section.embedded</string>
				        </dict>
				        <key>2</key>
				        <dict>
				            <key>name</key>
				            <string>entity.name.class</string>
				        </dict>
				    </dict>
				</dict>
    			<!-- Context property -->
				<dict>
					<key>match</key>
					<string>[@][a-zA-Z_]*</string>
					<key>name</key>
					<string>constant.other.color</string>
				</dict>
				<!-- Safe property -->
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>constant.other.color</string>
				</dict>
				<!-- Let statement -->
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<!-- Filters -->
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]*(\|)(\w+)(:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.eyebrow.delimiter.variable</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.color</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment</string>
						</dict>
					</dict>
				</dict>
				<!-- Quoted strings -->
				<dict>
					<key>match</key>
					<string>"(.+)"</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quotes</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.contents</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.html.eyebrow</string>
	<key>uuid</key>
	<string>6aa4dd19-fd95-4150-ac42-70d7ba08ff23</string>
</dict>
</plist>
